// NOTE: As of 11/2018 the JSON database app is producing invalid JSON.  
// These results correct all errors.
// http://www.workingweb.info/database/Code/Get/?codeId=ArtistDecade
// http://www.workingweb.info/database/Code/Get/?codeId=ArtistGenre

export const decades = 
{  
    "code":[  
       {  
          "codeId":"ArtistDecade",
          "value":1940,
          "description":"1940s"
       },
       {  
          "codeId":"ArtistDecade",
          "value":1950,
          "description":"1950s"
       },
       {  
          "codeId":"ArtistDecade",
          "value":1960,
          "description":"1960s"
       },
       {  
          "codeId":"ArtistDecade",
          "value":1970,
          "description":"1970s"
       },
       {  
          "codeId":"ArtistDecade",
          "value":1980,
          "description":"1980s"
       },
       {  
          "codeId":"ArtistDecade",
          "value":1990,
          "description":"1990s"
       },
       {  
          "codeId":"ArtistDecade",
          "value":2000,
          "description":"2000s"
       },
       {  
          "codeId":"ArtistDecade",
          "value":2010,
          "description":"2010s"
       }
    ]
};

export const genres = 
{  
    "code":[  
       {  
          "codeId":"ArtistGenre",
          "value":"CHILL",
          "description":"Chill"
       },
       {  
          "codeId":"ArtistGenre",
          "value":"CLASSIC",
          "description":"Classic"
       },
       {  
          "codeId":"ArtistGenre",
          "value":"COUNTRY",
          "description":"Country"
       },
       {  
          "codeId":"ArtistGenre",
          "value":"POP",
          "description":"Pop"
       },
       {  
          "codeId":"ArtistGenre",
          "value":"REGGAE",
          "description":"Reggae"
       },
       {  
          "codeId":"ArtistGenre",
          "value":"ROCK",
          "description":"Rock"
       },
       {  
          "codeId":"ArtistGenre",
          "value":"SOUL",
          "description":"Soul/R&B"
       }
    ]
};